apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: viatris-webapi
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: viatris-webapi
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/buhuaqiang/viat-net/VIAT.WebApi
      ref:
        branch: master
