---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: viatris-webapi
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: viatris-webapi
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: viatris-webapi
    tanzu.app.live.view.application.actuator.port: "9090"
spec:
  build:
    env:
    - name: DOTNET_CLI_TELEMETRY_OPTOUT
      value: "true"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  env:
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: "true"

  source:
    git:
      url: https://github.com/buhuaqiang/viat-net
      ref:
        branch: master

  serviceClaims:
    - name: database
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: customer-database-claim
